### ISSUE TITLE
这个包是对UBOOT有什么要求吗？

### ISSUE THREAD

**Issue by playbtceth** [rmoyulong/Lite_OpenWrt#1]
我本身是10.0内核的openwrt，已经刷了UBOOT，ITB,UBI,BIN怎么刷都刷不进，你编译的刷不进，自己云编译的也刷不进，刷完重启还是老系统。

**Comment by rmoyulong** [comment]
我刷的是志云uboot

**Comment by rmoyulong** [comment]
https://www.right.com.cn/FORUM/thread-8253375-1-1.html

**Comment by playbtceth** [comment]
这个固件不得不说有点东西，已经是uboot，108m大分区了，还要刷改分区固件……我想问一下，刷完这个，想再刷其他的，又要改回去不？

**Comment by playbtceth** [comment]
今天查了下资料，原因应该是ImmortalWrt不支持扩容的大分区。解决办法就是两个：1.刷回原版分区表 2.下载支持大分区的固件（带stock字样）
